// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeLQycDHYBW4DCtfO52ZlJ6gX71n4A784',
    appId: '1:1003477829831:web:2a2fe54f5295f1ce3f96e2',
    messagingSenderId: '1003477829831',
    projectId: 'schedit-cdd36',
    authDomain: 'schedit-cdd36.firebaseapp.com',
    storageBucket: 'schedit-cdd36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlirKSURb9l058Ga2ocyFehVZ7EEcOozo',
    appId: '1:1003477829831:android:47149441f95d26f03f96e2',
    messagingSenderId: '1003477829831',
    projectId: 'schedit-cdd36',
    storageBucket: 'schedit-cdd36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAECtA6BPr0TQnVcB29faZCgpO4-fHa8zo',
    appId: '1:1003477829831:ios:d18bcddbbb0a1a733f96e2',
    messagingSenderId: '1003477829831',
    projectId: 'schedit-cdd36',
    storageBucket: 'schedit-cdd36.firebasestorage.app',
    iosBundleId: 'com.example.shedit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAECtA6BPr0TQnVcB29faZCgpO4-fHa8zo',
    appId: '1:1003477829831:ios:d18bcddbbb0a1a733f96e2',
    messagingSenderId: '1003477829831',
    projectId: 'schedit-cdd36',
    storageBucket: 'schedit-cdd36.firebasestorage.app',
    iosBundleId: 'com.example.shedit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeLQycDHYBW4DCtfO52ZlJ6gX71n4A784',
    appId: '1:1003477829831:web:226939d7068b78853f96e2',
    messagingSenderId: '1003477829831',
    projectId: 'schedit-cdd36',
    authDomain: 'schedit-cdd36.firebaseapp.com',
    storageBucket: 'schedit-cdd36.firebasestorage.app',
  );

}